name: Prettier

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Prettify code
      uses: creyD/prettier_action@v4.3
      with:
        prettier_options: --write **/*.{js,md}
        only_changed: True
        github_token: ${{ secrets.WOLF_GITHUB_TOKEN }}
